package com.cloudbite.enums;

public enum OrderStatus {
    PENDING,
    PAYMENT_FAILED,
    CONFIRMED,
    PREPARING,
    READY_FOR_PICKUP,
    ACCEPTED,
    HEADING_TO_RESTAURANT,
    ARRIVED_AT_RESTAURANT,
    PICKED_UP,
    HEADING_TO_CUSTOMER,
    DELIVERED,
    CANCELLED
}
